// ext/src/ui/options/Whitelist.tsx
/* eslint-disable max-len */
"use strict";

import React, { Component } from "react";

import type { WhitelistItemData } from "../../background/whitelist";
import { REMOTE_MATCH_PATTERN_REGEX } from "../../lib/matchPattern";

const _ = browser.i18n.getMessage;

interface WhitelistProps {
    items: WhitelistItemData[];
    onChange: (items: WhitelistItemData[]) => void;
}
interface WhitelistState {
    addingNewItem: boolean;
}

/** Editable list component for site whitelist. */
export default class Whitelist extends Component<
    WhitelistProps,
    WhitelistState
> {
    state: WhitelistState = {
        addingNewItem: false
    };

    render() {
        return (
            <div className="whitelist">
                <ul className="whitelist__items">
                    {this.props.items.map((item, i) => (
                        <WhitelistItem
                            value={item}
                            onEdit={(oldValue, newValue) => {
                                // Replace item
                                this.props.onChange(
                                    this.props.items.map(item =>
                                        item.pattern === oldValue?.pattern
                                            ? newValue
                                            : item
                                    )
                                );
                            }}
                            onRemove={value => {
                                // Remove item
                                this.props.onChange(
                                    this.props.items.filter(
                                        item => item.pattern !== value?.pattern
                                    )
                                );
                            }}
                            key={i}
                        />
                    ))}

                    {this.state.addingNewItem && (
                        <WhitelistItem
                            isEditing={true}
                            onEdit={(__, newValue) => {
                                // Add new item
                                this.setState({ addingNewItem: false }, () => {
                                    this.props.onChange([
                                        ...this.props.items,
                                        newValue
                                    ]);
                                });
                            }}
                            onRemove={() => {
                                // Cancel adding new item
                                this.setState({ addingNewItem: false });
                            }}
                        />
                    )}
                </ul>

                <hr />

                <div className="whitelist__view-actions">
                    <button
                        className="whitelist__add-button ghost"
                        title={_("optionsSiteWhitelistAddItem")}
                        onClick={() => this.setState({ addingNewItem: true })}
                        type="button"
                    >
                        <img src="assets/photon_new.svg" alt="icon, add" />
                    </button>
                </div>
            </div>
        );
    }
}

interface WhitelistItemProps {
    value?: WhitelistItemData;
    /** Initial editing state */
    isEditing?: boolean;
    onEdit: (
        oldValue: WhitelistItemData | undefined,
        newValue: WhitelistItemData
    ) => void;
    onRemove: (value?: WhitelistItemData) => void;
}
interface WhitelistItemState {
    isEditing: boolean;
    editValue?: WhitelistItemData;
}

/** Editable item component for whitelist. */
class WhitelistItem extends Component<WhitelistItemProps, WhitelistItemState> {
    private inputElement: HTMLInputElement | null = null;

    constructor(props: WhitelistItemProps) {
        super(props);
        this.state = { isEditing: props.isEditing ?? false };

        this.beginEditing = this.beginEditing.bind(this);
        this.finishEditing = this.finishEditing.bind(this);
    }

    /** Sets editing state and focuses input field. */
    private beginEditing() {
        if (this.state.isEditing) return;

        this.setState(
            {
                isEditing: true,
                editValue: this.props.value
            },
            () => {
                this.inputElement?.focus();
                this.inputElement?.select();
            }
        );
    }

    /** Checks input validity and sends edit update. */
    private finishEditing() {
        if (!this.state.isEditing || !this.state.editValue) return;

        if (this.inputElement?.validity.valid) {
            this.props.onEdit(this.props.value, this.state.editValue);
            this.setState({
                isEditing: false,
                editValue: undefined
            });
        }
    }

    render() {
        const selectedClassName = this.state.isEditing
            ? "whitelist__item--selected"
            : "";

        return (
            <li className={`whitelist__item ${selectedClassName}`}>
                <div
                    className="whitelist__title"
                    onDoubleClick={this.beginEditing}
                >
                    {this.state.isEditing ? (
                        <input
                            ref={el => (this.inputElement = el)}
                            type="text"
                            className="whitelist__input-pattern"
                            value={this.state.editValue?.pattern}
                            pattern={REMOTE_MATCH_PATTERN_REGEX.source}
                            onChange={ev => {
                                this.setState(prevState => ({
                                    editValue: {
                                        ...prevState.editValue,
                                        pattern: ev.target.value
                                    }
                                }));
                            }}
                            onBlur={this.finishEditing}
                            onKeyPress={ev => {
                                if (ev.key === "Enter") {
                                    this.finishEditing();
                                }
                            }}
                        />
                    ) : (
                        this.props.value?.pattern
                    )}
                </div>

                <label className="whitelist__user-agent">
                    <input
                        type="checkbox"
                        checked={!this.props.value?.isUserAgentDisabled}
                        onChange={ev => {
                            if (!this.props.value) return;
                            this.props.onEdit(this.props.value, {
                                ...this.props.value,
                                isUserAgentDisabled: !ev.target.checked
                            });
                        }}
                    />
                    {_("optionsSiteWhitelistUserAgent")}
                </label>

                <button
                    className="whitelist__edit-button ghost"
                    title={_("optionsSiteWhitelistEditItem")}
                    onClick={this.beginEditing}
                    type="button"
                >
                    <img src="assets/photon_edit.svg" alt="icon, edit" />
                </button>

                <button
                    className="whitelist__remove-button ghost"
                    title={_("optionsSiteWhitelistRemoveItem")}
                    onClick={() => {
                        this.props.onRemove(this.props.value);
                    }}
                    type="button"
                >
                    <img src="assets/photon_delete.svg" alt="icon, remove" />
                </button>
            </li>
        );
    }
}

// extension/src/ui/options/Whitelist.svelte
<script lang="ts">
    import { tick } from "svelte";

    import type { WhitelistItemData } from "../../background/whitelist";

    import { REMOTE_MATCH_PATTERN_REGEX } from "../../lib/matchPattern";
    import type { Options } from "../../lib/options";

    import knownApps, { type KnownApp } from "../../cast/knownApps";
    import Option from "./Option.svelte";

    const _ = browser.i18n.getMessage;

    /** Whitelist items to display. */
    export let items: WhitelistItemData[];
    export let opts: Options;
    export let defaultUserAgent: Optional<string>;

    let isEditing = false;
    let isEditingValid = false;
    let editingIndex: number;
    let editingInput: HTMLInputElement;
    let editingValue: string;

    let expandedItemIndices = new Set<number>();

    let knownAppToAdd: Nullable<KnownApp> = null;
    $: filteredKnownApps = Object.values(knownApps).filter(app => {
        // If no pattern or name matches default media sender
        if (!app.matches || app.name === _("popupMediaTypeAppMedia")) {
            return false;
        }
        // Filter if pattern already in whitelist
        return !items.find(item => item.pattern === app.matches);
    });

    async function beginEditing(index: number) {
        if (isEditing) return;

        editingIndex = index;
        editingValue = items[index].pattern;
        isEditing = true;

        await tick();

        isEditingValid = editingInput.validity.valid;
        editingInput.focus();
        editingInput.select();
    }
    function finishEditing() {
        if (!isEditing || !isEditingValid) return;

        isEditing = false;
        items[editingIndex].pattern = editingValue;
    }

    async function onEditKeydown(ev: KeyboardEvent) {
        key: switch (ev.key) {
            // Finish editing on enter
            case "Enter":
                finishEditing();
                break;

            // Cancel editing (or adding new item) on escape
            case "Escape": {
                const originalValue = items[editingIndex];
                switch (originalValue.pattern) {
                    case "":
                        removeItem(editingIndex);
                        break key;
                    case editingValue:
                        finishEditing();
                        break key;
                }

                editingValue = originalValue.pattern;
                await tick();
                isEditingValid = editingInput.validity.valid;
                editingInput.select();

                break;
            }
        }
    }

    function onEditInput() {
        editingInput.setCustomValidity(
            // Has duplicate pattern
            items.some(
                (item, index) =>
                    index !== editingIndex && item.pattern === editingValue
            )
                ? _("optionsSiteWhitelistInvalidDuplicatePattern")
                : ""
        );

        isEditingValid = editingInput.validity.valid;
    }

    function addItem() {
        if (isEditing) return;

        if (knownAppToAdd?.matches) {
            items = [
                ...items,
                { pattern: knownAppToAdd.matches, isEnabled: true }
            ];
            knownAppToAdd = null;
        } else {
            items = [...items, { pattern: "", isEnabled: true }];
            beginEditing(items.length - 1);
        }
    }
    function removeItem(index: number) {
        if (isEditing) {
            if (index !== editingIndex) return;
            isEditing = false;
        }

        expandedItemIndices.delete(index);
        expandedItemIndices = expandedItemIndices;

        items.splice(index, 1);
        items = items;
    }
</script>

<div class="whitelist">
    <ul class="whitelist__items">
        {#each items as item, i}
            {@const isEditingItem = isEditing && editingIndex === i}
            {@const isItemExpanded = expandedItemIndices.has(i)}

            <li
                class="whitelist__item"
                class:whitelist__item--selected={isEditingItem}
                class:whitelist__item--expanded={isItemExpanded}
                class:whitelist__item--disabled={!item.isEnabled}
                class:whitelist__item--editing={isEditingItem}
            >
                {#if !isEditingItem}
                    <input
                        type="checkbox"
                        title={_("optionsSiteWhitelistItemEnabled")}
                        bind:checked={item.isEnabled}
                    />
                {/if}

                <div
                    class="whitelist__title"
                    on:dblclick={() => beginEditing(i)}
                >
                    {#if isEditingItem}
                        <input
                            type="text"
                            class="whitelist__input-pattern"
                            pattern={REMOTE_MATCH_PATTERN_REGEX.source}
                            required
                            title={_("optionsSiteWhitelistItemPattern")}
                            bind:this={editingInput}
                            bind:value={editingValue}
                            on:input={onEditInput}
                            on:keydown={onEditKeydown}
                            on:blur={finishEditing}
                        />
                    {:else}
                        {@const knownApp = Object.values(knownApps).find(
                            app => app.matches === item.pattern
                        )}
                        <div class="whitelist__pattern">
                            {item.pattern}
                        </div>
                        {#if knownApp}
                            <div class="whitelist__known-app">
                                &nbsp;({knownApp.name})
                            </div>
                        {/if}
                    {/if}
                </div>

                {#if !isEditingItem}
                    <button
                        type="button"
                        class="whitelist__edit-button ghost"
                        title={_("optionsSiteWhitelistEditItem")}
                        disabled={isEditing && !isEditingValid}
                        on:click={() => beginEditing(i)}
                    />
                {/if}

                <button
                    type="button"
                    class="whitelist__remove-button ghost"
                    title={_("optionsSiteWhitelistRemoveItem")}
                    disabled={isEditing && !isEditingItem && !isEditingValid}
                    on:click={() => removeItem(i)}
                />

                {#if !isEditingItem && opts.showAdvancedOptions}
                    <button
                        type="button"
                        class="whitelist__expand-button ghost"
                        title={_(
                            isItemExpanded
                                ? "optionsSiteWhitelistItemHideOptions"
                                : "optionsSiteWhitelistItemShowOptions"
                        )}
                        on:click={() => {
                            // Toggle expanded state
                            if (isItemExpanded) {
                                expandedItemIndices.delete(i);
                            } else {
                                expandedItemIndices.add(i);
                            }
                            expandedItemIndices = expandedItemIndices;
                        }}
                    />

                    {#if isItemExpanded}
                        <div class="whitelist__expanded">
                            <Option
                                id="isUserAgentDisabled-{i}"
                                label={_(
                                    "optionsSiteWhitelistUserAgentDisabled"
                                )}
                                description={_(
                                    "optionsSiteWhitelistUserAgentDisabledDescription"
                                )}
                                type="checkbox"
                                bind:checked={item.isUserAgentDisabled}
                                inline
                            />

                            <Option
                                id="customUserAgentString-{i}"
                                label={_(
                                    "optionsSiteWhitelistSiteSpecificUserAgent"
                                )}
                                description={_(
                                    "optionsSiteWhitelistSiteSpecificUserAgentDescription"
                                )}
                                bind:value={item.customUserAgent}
                                placeholder={opts.siteWhitelistCustomUserAgent ||
                                    defaultUserAgent}
                            />
                        </div>
                    {/if}
                {/if}
            </li>
        {/each}
    </ul>

    <hr />

    <div class="whitelist__view-actions">
        <div class="select-wrapper">
            <select bind:value={knownAppToAdd}>
                <option value={null}>
                    {_("optionsSiteWhitelistKnownAppsCustomApp")}
                </option>
                {#each filteredKnownApps as knownApp}
                    <option value={knownApp}>
                        {knownApp.name}
                    </option>
                {/each}
            </select>
        </div>
        <button
            class="whitelist__add-button ghost"
            title={_("optionsSiteWhitelistAddItem")}
            on:click={addItem}
            type="button"
        />
    </div>
</div>
