// ext/src/ui/popup/Popup.svelte
<script lang="ts">
    import { afterUpdate, onMount, tick } from "svelte";

    import LoadingIndicator from "../LoadingIndicator.svelte";

    import messaging, { Message, Port } from "../../messaging";
    import options, { Options } from "../../lib/options";
    import { RemoteMatchPattern } from "../../lib/matchPattern";

    import {
        ReceiverDevice,
        ReceiverSelectionActionType,
        ReceiverSelectorMediaType,
        ReceiverSelectorPageInfo
    } from "../../types";

    import knownApps, { KnownApp } from "../../cast/knownApps";
    import { hasRequiredCapabilities } from "../../cast/utils";

    const _ = browser.i18n.getMessage;

    /** List of devices to show in receiver list. */
    let receiverDevices: ReceiverDevice[] = [];

    /** Currently selected media type. */
    let mediaType = ReceiverSelectorMediaType.App;
    /** Media types available to select. */
    let availableMediaTypes = ReceiverSelectorMediaType.App;

    /** Sender app ID (if available). */
    let appId: Optional<string>;
    /** Page info (if launched from page context). */
    let pageInfo: Optional<ReceiverSelectorPageInfo>;

    /** App details (if matches known app). */
    let knownApp: Nullable<KnownApp> = null;

    /** Whether current page URL matches a whitelist pattern. */
    let isPageWhitelisted = false;

    /** Whether casting to a device been initiated from this selector. */
    let isConnecting = false;
    let connectingId: Nullable<string> = null;

    /** Extension options */
    let opts: Nullable<Options> = null;

    $: isMediaTypeAvailable = !!(availableMediaTypes & mediaType);
    $: isAppMediaTypeAvailable = !!(
        availableMediaTypes & ReceiverSelectorMediaType.App
    );

    /** Whether to display whitelist suggestion banner. */
    $: shouldSuggestWhitelist =
        // If we know the app
        knownApp &&
        // If the whitelist is enabled
        opts?.siteWhitelistEnabled &&
        // If the page is not whitelisted
        !isPageWhitelisted &&
        // If an app is not already loaded on the page
        !(availableMediaTypes & ReceiverSelectorMediaType.App);

    let port: Nullable<Port> = null;
    let browserWindow: Nullable<browser.windows.Window> = null;
    let resizeObserver = new ResizeObserver(() => fitWindowHeight());

    onMount(async () => {
        port = messaging.connect({ name: "popup" });
        port.onMessage.addListener(onMessage);

        browserWindow = await browser.windows.getCurrent();

        opts = await options.getAll();
        options.addEventListener("changed", async ev => {
            opts = await options.getAll();

            /**
             * Update available media types and ensure selected media
             * type is valid.
             */
            if (ev.detail.includes("mirroringEnabled")) {
                const mirroringMediaTypes =
                    ReceiverSelectorMediaType.Tab |
                    ReceiverSelectorMediaType.Screen;

                if (!opts.mirroringEnabled) {
                    availableMediaTypes &= ~mirroringMediaTypes;
                } else {
                    availableMediaTypes |= mirroringMediaTypes;
                }

                if (!(availableMediaTypes & mediaType)) {
                    if (availableMediaTypes & ReceiverSelectorMediaType.App) {
                        mediaType = ReceiverSelectorMediaType.App;
                    } else if (
                        availableMediaTypes & ReceiverSelectorMediaType.Tab
                    ) {
                        mediaType = ReceiverSelectorMediaType.Tab;
                    } else {
                        mediaType = ReceiverSelectorMediaType.App;
                    }
                }
            }
        });

        updateKnownApp();

        window.addEventListener("contextmenu", onContextMenu);
        browser.menus.onClicked.addListener(onMenuClicked);
        browser.menus.onShown.addListener(onMenuShown);

        return () => {
            port?.disconnect();
            resizeObserver.disconnect();

            window.addEventListener("contextmenu", onContextMenu);
            browser.menus.onClicked.removeListener(onMenuClicked);
            browser.menus.onShown.removeListener(onMenuShown);
        };
    });

    afterUpdate(async () => {
        await tick();
        fitWindowHeight();
    });

    function onMessage(message: Message) {
        switch (message.subject) {
            case "popup:init":
                appId = message.data.appId;
                pageInfo = message.data.pageInfo;
                break;

            case "popup:close":
                window.close();
                break;

            case "popup:update": {
                /**
                 * Filter receiver devices without the required
                 * capabilities.
                 */
                receiverDevices = message.data.receiverDevices.filter(device =>
                    hasRequiredCapabilities(
                        device,
                        pageInfo?.sessionRequest?.capabilities
                    )
                );

                if (
                    message.data.availableMediaTypes !== undefined &&
                    message.data.defaultMediaType !== undefined
                ) {
                    availableMediaTypes = message.data.availableMediaTypes;

                    if (availableMediaTypes & message.data.defaultMediaType) {
                        mediaType = message.data.defaultMediaType;
                    }
                }

                updateKnownApp();
                break;
            }
        }
    }

    /** Resize browser window to fit content height. */
    function fitWindowHeight() {
        if (browserWindow?.id === undefined) return;
        browser.windows.update(browserWindow.id, {
            height:
                document.body.clientHeight +
                (window.outerHeight - window.innerHeight)
        });
    }

    function updateKnownApp() {
        let newKnownApp: Nullable<KnownApp> = null;

        /**
         * Check knownApps for an app with an ID matching the registered
         * app on the target page.
         */
        if (isAppMediaTypeAvailable && appId) {
            newKnownApp = knownApps[appId];
        } else if (pageInfo) {
            const pageUrl = pageInfo.url;

            /**
             * Or if there isn't an registered app, check for an app
             * with a match pattern matching the target page URL.
             */
            for (const [, app] of Object.entries(knownApps)) {
                if (!app.matches) {
                    continue;
                }

                const pattern = new RemoteMatchPattern(app.matches);
                if (pattern.matches(pageUrl)) {
                    newKnownApp = app;
                    break;
                }
            }
        }

        // Check if target page URL is whitelisted.
        if (pageInfo && opts?.siteWhitelist) {
            for (const item of opts.siteWhitelist) {
                const pattern = new RemoteMatchPattern(item.pattern);
                if (pattern.matches(pageInfo.url)) {
                    isPageWhitelisted = true;
                    break;
                }
            }
        }

        knownApp = newKnownApp;
    }

    async function addToWhitelist(
        app: KnownApp,
        pageInfo: ReceiverSelectorPageInfo
    ) {
        if (!app.matches) {
            return;
        }

        const whitelist = await options.get("siteWhitelist");
        if (!whitelist.find(item => item.pattern === app.matches)) {
            whitelist.push({ pattern: app.matches });
            await options.set("siteWhitelist", whitelist);

            await browser.tabs.reload(pageInfo.tabId);
            window.close();
        }
    }

    function onContextMenu(ev: MouseEvent) {
        if (!(ev.target instanceof Element)) return;

        const receiverElement = ev.target.closest(".receiver");
        if (receiverElement) {
            browser.menus.overrideContext({
                showDefaults: false
            });
        }
    }

    function getDeviceFromElement(target: Element) {
        const receiverElement = target.closest(".receiver");
        if (!receiverElement) return;

        const receiverElementIndex = [
            // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
            ...receiverElement.parentElement!.children
        ].indexOf(receiverElement);

        // Match by index rendered receiver element to device array
        if (receiverElementIndex > -1) {
            return receiverDevices[receiverElementIndex];
        }
    }

    /** Handle show events for receiver context menus. */
    function onMenuShown(info: browser.menus._OnShownInfo) {
        if (!info.targetElementId) return;
        const target = browser.menus.getTargetElement(info.targetElementId);
        if (!target) return;

        const device = getDeviceFromElement(target);
        if (!device) {
            browser.menus.update("popup_cast", { visible: false });
            browser.menus.update("popup_stop", { visible: false });
        } else {
            const app = device.status?.applications?.[0];
            const isAppRunning = !!(app && !app.isIdleScreen);

            browser.menus.update("popup_cast", {
                visible: true,
                title: _("popupCastMenuTitle", device.friendlyName),
                enabled:
                    // Not already connecting to a receiver
                    !isConnecting &&
                    // Selected media type available
                    isMediaTypeAvailable
            });

            browser.menus.update("popup_stop", {
                visible: isAppRunning,
                title: isAppRunning
                    ? _("popupStopMenuTitle", [
                          app.displayName,
                          device.friendlyName
                      ])
                    : ""
            });
        }

        browser.menus.refresh();
    }

    /** Handle click events for receiver context menus. */
    function onMenuClicked(info: browser.menus.OnClickData) {
        if (
            info.menuItemId !== "popup_cast" &&
            info.menuItemId !== "popup_stop"
        ) {
            return;
        }

        if (!info.targetElementId) return;
        const target = browser.menus.getTargetElement(info.targetElementId);
        if (!target) return;

        const device = getDeviceFromElement(target);
        if (!device) return;

        switch (info.menuItemId) {
            case "popup_cast":
                onReceiverCast(device);
                break;
            case "popup_stop":
                onReceiverStop(device);
                break;
        }
    }

    function onReceiverCast(receiverDevice: ReceiverDevice) {
        isConnecting = true;
        connectingId = receiverDevice.id;

        port?.postMessage({
            subject: "receiverSelector:selected",
            data: {
                receiverDevice,
                actionType: ReceiverSelectionActionType.Cast,
                mediaType
            }
        });
    }

    function onReceiverStop(receiverDevice: ReceiverDevice) {
        port?.postMessage({
            subject: "receiverSelector:stop",
            data: {
                receiverDevice,
                actionType: ReceiverSelectionActionType.Stop
            }
        });
    }
</script>

<div class="whitelist-banner" hidden={!shouldSuggestWhitelist}>
    <img src="photon_info.svg" alt="icon, info" />
    {_("popupWhitelistNotWhitelisted", knownApp?.name)}
    <button
        on:click={() => {
            if (!knownApp || !pageInfo) return;
            addToWhitelist(knownApp, pageInfo);
        }}
    >
        {_("popupWhitelistAddToWhitelist")}
    </button>
</div>

<div class="media-type-select">
    <div class="media-type-select__label-cast">
        {_("popupMediaSelectCastLabel")}
    </div>
    <div
        class="select-wrapper"
        class:select-wrapper--disabled={availableMediaTypes ===
            ReceiverSelectorMediaType.None}
    >
        <select
            class="media-type-select__dropdown"
            bind:value={mediaType}
            disabled={availableMediaTypes === ReceiverSelectorMediaType.None}
        >
            <option
                value={ReceiverSelectorMediaType.App}
                disabled={!isAppMediaTypeAvailable}
            >
                {knownApp?.name ?? _("popupMediaTypeApp")}
            </option>

            {#if opts?.mirroringEnabled}
                <option
                    value={ReceiverSelectorMediaType.Tab}
                    disabled={!(
                        availableMediaTypes & ReceiverSelectorMediaType.Tab
                    )}
                >
                    {_("popupMediaTypeTab")}
                </option>
                <option
                    value={ReceiverSelectorMediaType.Screen}
                    disabled={!(
                        availableMediaTypes & ReceiverSelectorMediaType.Screen
                    )}
                >
                    {_("popupMediaTypeScreen")}
                </option>
            {/if}
        </select>
    </div>
    <div class="media-type-select__label-to">
        {_("popupMediaSelectToLabel")}
    </div>
</div>

<ul class="receivers">
    {#if !receiverDevices.length}
        <div class="receivers__not-found">
            {_("popupNoReceiversFound")}
        </div>
    {:else}
        {#each receiverDevices as device}
            {@const application = device.status?.applications?.[0]}
            {@const isDeviceConnecting =
                isConnecting && connectingId === device.id}

            <li class="receiver">
                <div class="receiver__name">
                    {device.friendlyName}
                </div>
                <div class="receiver__address">
                    {application && !application.isIdleScreen
                        ? application.statusText
                        : `${device.host}:${device.port}`}
                </div>
                <button
                    class="button receiver__connect"
                    on:click={() => onReceiverCast(device)}
                    disabled={isConnecting ||
                        isDeviceConnecting ||
                        !isMediaTypeAvailable}
                >
                    {#if isDeviceConnecting}
                        {_("popupCastingButtonTitle", "")}<LoadingIndicator />
                    {:else}
                        {_("popupCastButtonTitle")}
                    {/if}
                </button>
            </li>
        {/each}
    {/if}
</ul>

// ext/src/ui/popup/index.tsx
/* eslint-disable max-len */
"use strict";

import React, { Component } from "react";
import ReactDOM from "react-dom";

import knownApps, { KnownApp } from "../../cast/knownApps";
import options from "../../lib/options";

import messaging, { Message, Port } from "../../messaging";
import { getNextEllipsis } from "../../lib/utils";
import { RemoteMatchPattern } from "../../lib/matchPattern";
import { ReceiverDevice } from "../../types";

import {
    ReceiverSelectionActionType,
    ReceiverSelectorMediaType
} from "../../background/receiverSelector";
import { PageInfo } from "../../background/receiverSelector/ReceiverSelector";

const _ = browser.i18n.getMessage;

// macOS styles
browser.runtime.getPlatformInfo().then(platformInfo => {
    if (platformInfo.os === "mac") {
        const link = document.createElement("link");
        link.rel = "stylesheet";
        link.href = "styles/mac.css";
        document.head.appendChild(link);
    }
});

interface PopupAppProps {}
interface PopupAppState {
    receivers: ReceiverDevice[];
    mediaType: ReceiverSelectorMediaType;
    availableMediaTypes: ReceiverSelectorMediaType;
    isLoading: boolean;

    filePath?: string;
    appId?: string;
    pageInfo?: PageInfo;

    mirroringEnabled: boolean;
    userAgentWhitelistEnabled: boolean;
    userAgentWhitelist: string[];

    knownApp?: KnownApp;
    isPageWhitelisted: boolean;
}

class PopupApp extends Component<PopupAppProps, PopupAppState> {
    private port?: Port;
    private win?: browser.windows.Window;
    private defaultMediaType?: ReceiverSelectorMediaType;

    constructor(props: PopupAppProps) {
        super(props);

        this.state = {
            receivers: [],
            mediaType: ReceiverSelectorMediaType.App,
            availableMediaTypes: ReceiverSelectorMediaType.App,
            isLoading: false,
            mirroringEnabled: false,
            userAgentWhitelistEnabled: true,
            userAgentWhitelist: [],
            isPageWhitelisted: false
        };

        // Store window ref
        browser.windows.getCurrent().then(win => {
            this.win = win;
        });

        new ResizeObserver(() => {
            this.updateWindowHeight();
        }).observe(document.body);

        this.onAddToWhitelist = this.onAddToWhitelist.bind(this);
        this.onSelectChange = this.onSelectChange.bind(this);
        this.onCast = this.onCast.bind(this);
        this.onStop = this.onStop.bind(this);
    }

    public updateWindowHeight() {
        if (this.win?.id === undefined) {
            return;
        }

        const frameHeight = window.outerHeight - window.innerHeight;
        const windowHeight = document.body.clientHeight + frameHeight;

        browser.windows.update(this.win.id, {
            height: windowHeight
        });
    }

    public async componentDidMount() {
        this.port = messaging.connect({ name: "popup" });

        this.port.onMessage.addListener((message: Message) => {
            switch (message.subject) {
                case "popup:init": {
                    this.setState({
                        appId: message.data?.appId,
                        pageInfo: message.data?.pageInfo
                    });

                    break;
                }

                case "popup:update": {
                    const { receivers, availableMediaTypes, defaultMediaType } =
                        message.data;

                    this.setState({ receivers });

                    if (
                        availableMediaTypes !== undefined &&
                        defaultMediaType !== undefined
                    ) {
                        this.defaultMediaType = defaultMediaType;
                        this.setState({
                            availableMediaTypes,
                            mediaType: defaultMediaType
                        });
                    }

                    this.updateKnownApp();

                    break;
                }

                case "popup:close": {
                    window.close();
                    break;
                }
            }
        });

        const opts = await options.getAll();

        this.setState({
            mirroringEnabled: opts.mirroringEnabled,
            userAgentWhitelistEnabled: opts.userAgentWhitelistEnabled,
            userAgentWhitelist: opts.userAgentWhitelist
        });

        this.updateKnownApp();
    }

    public componentDidUpdate() {
        setTimeout(() => {
            this.updateWindowHeight();
        }, 1);
    }

    private updateKnownApp() {
        const isAppMediaTypeAvailable = !!(
            this.state.availableMediaTypes & ReceiverSelectorMediaType.App
        );

        let knownApp: Nullable<KnownApp> = null;

        /**
         * Check knownApps for an app with an ID matching the registered
         * app on the target page.
         * Or if there isn't an registered app, check for an app with a
         * match pattern matching the target page URL.
         */
        if (isAppMediaTypeAvailable && this.state.appId) {
            knownApp = knownApps[this.state.appId];
        } else if (this.state.pageInfo) {
            const pageUrl = this.state.pageInfo.url;

            for (const [, app] of Object.entries(knownApps)) {
                if (!app.matches) {
                    continue;
                }

                const pattern = new RemoteMatchPattern(app.matches);
                if (pattern.matches(pageUrl)) {
                    knownApp = app;
                    break;
                }
            }
        }

        let isPageWhitelisted = false;

        /**
         * Check if target page URL is whitelisted.
         */
        if (this.state.pageInfo) {
            for (const patternString of this.state.userAgentWhitelist) {
                const pattern = new RemoteMatchPattern(patternString);
                if (pattern.matches(this.state.pageInfo.url)) {
                    isPageWhitelisted = true;
                    break;
                }
            }
        }

        this.setState({
            knownApp: knownApp ?? undefined,
            isPageWhitelisted
        });
    }

    public render() {
        /*

        // TODO: Add file support back to popup

        let truncatedFileName: string;

        if (this.state.filePath) {
            const filePath = this.state.filePath;
            const fileName = filePath.substring(filePath.lastIndexOf("/") + 1);

            truncatedFileName = fileName.length > 12
                ? `${fileName.substring(0, 12)}...`
                : fileName;
        }
        */

        const isAppMediaTypeSelected =
            this.state.mediaType === ReceiverSelectorMediaType.App;
        const isTabMediaTypeSelected =
            this.state.mediaType === ReceiverSelectorMediaType.Tab;
        const isScreenMediaTypeSelected =
            this.state.mediaType === ReceiverSelectorMediaType.Screen;

        const isSelectedMediaTypeAvailable = !!(
            this.state.availableMediaTypes & this.state.mediaType
        );
        const isAppMediaTypeAvailable = !!(
            this.state.availableMediaTypes & ReceiverSelectorMediaType.App
        );

        return (
            <>
                <div
                    className="whitelist-suggest"
                    hidden={
                        // If we don't know the app
                        !this.state.knownApp ||
                        // If the whitelist is disabled
                        !this.state.userAgentWhitelistEnabled ||
                        // If the whitelist is enabled, and the page is whitelisted
                        (this.state.userAgentWhitelistEnabled &&
                            this.state.isPageWhitelisted) ||
                        // If an app is already loaded on the page
                        isAppMediaTypeAvailable
                    }
                >
                    <img src="photon_info.svg" />
                    {_(
                        "popupWhitelistNotWhitelisted",
                        this.state.knownApp?.name
                    )}
                    <button
                        onClick={() => {
                            if (!this.state.knownApp || !this.state.pageInfo) {
                                return;
                            }

                            this.onAddToWhitelist(
                                this.state.knownApp,
                                this.state.pageInfo
                            );
                        }}
                    >
                        {_("popupWhitelistAddToWhitelist")}
                    </button>
                </div>
                <div className="media-select">
                    <div className="media-select__label-cast">
                        {_("popupMediaSelectCastLabel")}
                    </div>
                    <div className="select-wrapper">
                        <select
                            onChange={this.onSelectChange}
                            className="media-select__dropdown"
                            disabled={
                                this.state.availableMediaTypes ===
                                ReceiverSelectorMediaType.None
                            }
                        >
                            <option
                                value={ReceiverSelectorMediaType.App}
                                selected={isAppMediaTypeSelected}
                                disabled={!isAppMediaTypeAvailable}
                            >
                                {this.state.knownApp?.name ??
                                    _("popupMediaTypeApp")}
                            </option>

                            {this.state.mirroringEnabled && (
                                <>
                                    <option
                                        value={ReceiverSelectorMediaType.Tab}
                                        selected={isTabMediaTypeSelected}
                                        disabled={
                                            !(
                                                this.state.availableMediaTypes &
                                                ReceiverSelectorMediaType.Tab
                                            )
                                        }
                                    >
                                        {_("popupMediaTypeTab")}
                                    </option>
                                    <option
                                        value={ReceiverSelectorMediaType.Screen}
                                        selected={isScreenMediaTypeSelected}
                                        disabled={
                                            !(
                                                this.state.availableMediaTypes &
                                                ReceiverSelectorMediaType.Screen
                                            )
                                        }
                                    >
                                        {_("popupMediaTypeScreen")}
                                    </option>
                                </>
                            )}
                        </select>
                    </div>
                    <div className="media-select__label-to">
                        {_("popupMediaSelectToLabel")}
                    </div>
                </div>
                <ul className="receivers">
                    {this.state.receivers && this.state.receivers.length ? (
                        this.state.receivers.map((receiver, i) => (
                            <ReceiverEntry
                                receiver={receiver}
                                onCast={this.onCast}
                                onStop={this.onStop}
                                isLoading={this.state.isLoading}
                                canCast={isSelectedMediaTypeAvailable}
                                key={i}
                            />
                        ))
                    ) : (
                        <div className="receivers__not-found">
                            {_("popupNoReceiversFound")}
                        </div>
                    )}
                </ul>
            </>
        );
    }

    private async onAddToWhitelist(app: KnownApp, pageInfo: PageInfo) {
        if (!app.matches) {
            return;
        }

        const whitelist = await options.get("userAgentWhitelist");
        if (!whitelist.includes(app.matches)) {
            whitelist.push(app.matches);
            await options.set("userAgentWhitelist", whitelist);

            await browser.tabs.reload(pageInfo.tabId);
            window.close();
        }
    }

    private onCast(receiver: ReceiverDevice) {
        this.setState({
            isLoading: true
        });

        this.port?.postMessage({
            subject: "receiverSelector:selected",
            data: {
                actionType: ReceiverSelectionActionType.Cast,
                receiver,
                mediaType: this.state.mediaType,
                filePath: this.state.filePath
            }
        });
    }

    private onStop(receiver: ReceiverDevice) {
        this.port?.postMessage({
            subject: "receiverSelector:stop",
            data: {
                actionType: ReceiverSelectionActionType.Stop,
                receiver
            }
        });
    }

    private onSelectChange(ev: React.ChangeEvent<HTMLSelectElement>) {
        const mediaType = parseInt(ev.target.value);

        if (mediaType === ReceiverSelectorMediaType.File) {
            const fileUrl = window.prompt();
            if (fileUrl) {
                this.setState({
                    mediaType,
                    filePath: fileUrl
                });

                return;
            }

            // Set media type to default if failed to set filePath
            if (this.defaultMediaType) {
                this.setState({
                    mediaType: this.defaultMediaType
                });
            }
        } else {
            this.setState({
                mediaType
            });
        }

        this.setState({
            filePath: undefined
        });
    }
}

interface ReceiverEntryProps {
    receiver: ReceiverDevice;
    isLoading: boolean;
    canCast: boolean;
    onCast(receiver: ReceiverDevice): void;
    onStop(receiver: ReceiverDevice): void;
}

interface ReceiverEntryState {
    ellipsis: string;
    isLoading: boolean;
    showAlternateAction: boolean;
}

class ReceiverEntry extends Component<ReceiverEntryProps, ReceiverEntryState> {
    constructor(props: ReceiverEntryProps) {
        super(props);

        this.state = {
            ellipsis: "",
            isLoading: false,
            showAlternateAction: false
        };

        const handleActionKeyEvents = (ev: KeyboardEvent) => {
            if (ev.key === "Alt" || ev.key === "Shift") {
                this.setState({
                    // Only enable on keydown, otherwise disable
                    showAlternateAction: ev.type === "keydown"
                });
            }
        };

        window.addEventListener("keydown", handleActionKeyEvents);
        window.addEventListener("keyup", handleActionKeyEvents);

        window.addEventListener("blur", () => {
            this.setState({
                showAlternateAction: false
            });
        });

        this.handleCast = this.handleCast.bind(this);
    }

    public render() {
        const { status } = this.props.receiver;
        const application = status?.applications?.[0];

        return (
            <li className="receiver">
                <div className="receiver__name">
                    {this.props.receiver.friendlyName}
                </div>
                <div className="receiver__address">
                    {application && !application.isIdleScreen
                        ? application.statusText
                        : `${this.props.receiver.host}:${this.props.receiver.port}`}
                </div>
                <button
                    className="button receiver__connect"
                    onClick={this.handleCast}
                    disabled={
                        this.state.showAlternateAction
                            ? !application || application.isIdleScreen
                            : this.props.isLoading || !this.props.canCast
                    }
                >
                    {this.state.isLoading
                        ? _(
                              "popupCastingButtonTitle",
                              this.state.isLoading ? this.state.ellipsis : ""
                          )
                        : this.state.showAlternateAction
                        ? _("popupStopButtonTitle")
                        : _("popupCastButtonTitle")}
                </button>
            </li>
        );
    }

    private handleCast() {
        const { status } = this.props.receiver;
        if (!status) {
            return;
        }

        const application = status.applications?.[0];

        if (this.state.showAlternateAction) {
            this.props.onStop(this.props.receiver);
        } else {
            this.props.onCast(this.props.receiver);

            this.setState({
                isLoading: true
            });

            setInterval(() => {
                this.setState(state => ({
                    ellipsis: getNextEllipsis(state.ellipsis)
                }));
            }, 500);
        }
    }
}

// Render after CSS has loaded
window.addEventListener("load", () => {
    ReactDOM.render(<PopupApp />, document.querySelector("#root"));
});

window.addEventListener("contextmenu", () => {
    browser.menus.overrideContext({
        showDefaults: false
    });
});
