// ext/src/ui/options/Whitelist.tsx
/* eslint-disable max-len */
"use strict";

import React, { Component } from "react";

import type { WhitelistItemData } from "../../background/whitelist";
import { REMOTE_MATCH_PATTERN_REGEX } from "../../lib/matchPattern";

const _ = browser.i18n.getMessage;

interface WhitelistProps {
    items: WhitelistItemData[];
    onChange: (items: WhitelistItemData[]) => void;
}
interface WhitelistState {
    addingNewItem: boolean;
}

/** Editable list component for site whitelist. */
export default class Whitelist extends Component<
    WhitelistProps,
    WhitelistState
> {
    state: WhitelistState = {
        addingNewItem: false
    };

    render() {
        return (
            <div className="whitelist">
                <ul className="whitelist__items">
                    {this.props.items.map((item, i) => (
                        <WhitelistItem
                            value={item}
                            onEdit={(oldValue, newValue) => {
                                // Replace item
                                this.props.onChange(
                                    this.props.items.map(item =>
                                        item.pattern === oldValue?.pattern
                                            ? newValue
                                            : item
                                    )
                                );
                            }}
                            onRemove={value => {
                                // Remove item
                                this.props.onChange(
                                    this.props.items.filter(
                                        item => item.pattern !== value?.pattern
                                    )
                                );
                            }}
                            key={i}
                        />
                    ))}

                    {this.state.addingNewItem && (
                        <WhitelistItem
                            isEditing={true}
                            onEdit={(__, newValue) => {
                                // Add new item
                                this.setState({ addingNewItem: false }, () => {
                                    this.props.onChange([
                                        ...this.props.items,
                                        newValue
                                    ]);
                                });
                            }}
                            onRemove={() => {
                                // Cancel adding new item
                                this.setState({ addingNewItem: false });
                            }}
                        />
                    )}
                </ul>

                <hr />

                <div className="whitelist__view-actions">
                    <button
                        className="whitelist__add-button ghost"
                        title={_("optionsSiteWhitelistAddItem")}
                        onClick={() => this.setState({ addingNewItem: true })}
                        type="button"
                    >
                        <img src="assets/photon_new.svg" alt="icon, add" />
                    </button>
                </div>
            </div>
        );
    }
}

interface WhitelistItemProps {
    value?: WhitelistItemData;
    /** Initial editing state */
    isEditing?: boolean;
    onEdit: (
        oldValue: WhitelistItemData | undefined,
        newValue: WhitelistItemData
    ) => void;
    onRemove: (value?: WhitelistItemData) => void;
}
interface WhitelistItemState {
    isEditing: boolean;
    editValue?: WhitelistItemData;
}

/** Editable item component for whitelist. */
class WhitelistItem extends Component<WhitelistItemProps, WhitelistItemState> {
    private inputElement: HTMLInputElement | null = null;

    constructor(props: WhitelistItemProps) {
        super(props);
        this.state = { isEditing: props.isEditing ?? false };

        this.beginEditing = this.beginEditing.bind(this);
        this.finishEditing = this.finishEditing.bind(this);
    }

    /** Sets editing state and focuses input field. */
    private beginEditing() {
        if (this.state.isEditing) return;

        this.setState(
            {
                isEditing: true,
                editValue: this.props.value
            },
            () => {
                this.inputElement?.focus();
                this.inputElement?.select();
            }
        );
    }

    /** Checks input validity and sends edit update. */
    private finishEditing() {
        if (!this.state.isEditing || !this.state.editValue) return;

        if (this.inputElement?.validity.valid) {
            this.props.onEdit(this.props.value, this.state.editValue);
            this.setState({
                isEditing: false,
                editValue: undefined
            });
        }
    }

    render() {
        const selectedClassName = this.state.isEditing
            ? "whitelist__item--selected"
            : "";

        return (
            <li className={`whitelist__item ${selectedClassName}`}>
                <div
                    className="whitelist__title"
                    onDoubleClick={this.beginEditing}
                >
                    {this.state.isEditing ? (
                        <input
                            ref={el => (this.inputElement = el)}
                            type="text"
                            className="whitelist__input-pattern"
                            value={this.state.editValue?.pattern}
                            pattern={REMOTE_MATCH_PATTERN_REGEX.source}
                            onChange={ev => {
                                this.setState(prevState => ({
                                    editValue: {
                                        ...prevState.editValue,
                                        pattern: ev.target.value
                                    }
                                }));
                            }}
                            onBlur={this.finishEditing}
                            onKeyPress={ev => {
                                if (ev.key === "Enter") {
                                    this.finishEditing();
                                }
                            }}
                        />
                    ) : (
                        this.props.value?.pattern
                    )}
                </div>

                <label className="whitelist__user-agent">
                    <input
                        type="checkbox"
                        checked={!this.props.value?.isUserAgentDisabled}
                        onChange={ev => {
                            if (!this.props.value) return;
                            this.props.onEdit(this.props.value, {
                                ...this.props.value,
                                isUserAgentDisabled: !ev.target.checked
                            });
                        }}
                    />
                    {_("optionsSiteWhitelistUserAgent")}
                </label>

                <button
                    className="whitelist__edit-button ghost"
                    title={_("optionsSiteWhitelistEditItem")}
                    onClick={this.beginEditing}
                    type="button"
                >
                    <img src="assets/photon_edit.svg" alt="icon, edit" />
                </button>

                <button
                    className="whitelist__remove-button ghost"
                    title={_("optionsSiteWhitelistRemoveItem")}
                    onClick={() => {
                        this.props.onRemove(this.props.value);
                    }}
                    type="button"
                >
                    <img src="assets/photon_delete.svg" alt="icon, remove" />
                </button>
            </li>
        );
    }
}

// ext/src/ui/options/Whitelist.svelte
<script lang="ts">
    import { tick } from "svelte";

    import { WhitelistItemData } from "../../background/whitelist";
    import { REMOTE_MATCH_PATTERN_REGEX } from "../../lib/matchPattern";

    void REMOTE_MATCH_PATTERN_REGEX;

    const _ = browser.i18n.getMessage;

    /** Whitelist items to display. */
    export let items: WhitelistItemData[];

    let isEditing = false;
    let isEditingValid = false;
    let editingIndex: number;
    let editingInput: HTMLInputElement;
    let editingValue: string;

    async function beginEditing(index: number) {
        if (isEditing) return;

        editingIndex = index;
        editingValue = items[index].pattern;
        isEditing = true;

        await tick();

        isEditingValid = editingInput.validity.valid;
        editingInput.focus();
        editingInput.select();
    }
    function finishEditing() {
        if (!isEditing || !isEditingValid) return;

        isEditing = false;
        items[editingIndex].pattern = editingValue;
    }

    function checkEditValidity() {
        editingInput.setCustomValidity(
            // Has duplicate pattern
            items.some(
                (item, index) =>
                    index !== editingIndex && item.pattern === editingValue
            )
                ? _("optionsSiteWhitelistInvalidDuplicatePattern")
                : ""
        );

        isEditingValid = editingInput.validity.valid;
    }

    function addItem() {
        if (isEditing) return;
        items = [...items, { pattern: "" }];
        beginEditing(items.length - 1);
    }
    function removeItem(index: number) {
        if (isEditing) {
            if (index !== editingIndex) return;
            isEditing = false;
        }

        items.splice(index, 1);
        items = items;
    }
</script>

<div class="whitelist">
    <ul class="whitelist__items">
        {#each items as item, i}
            {@const isEditingItem = isEditing && editingIndex === i}

            <li
                class="whitelist__item"
                class:whitelist__item--selected={isEditingItem}
                on:dblclick={() => beginEditing(i)}
            >
                <div class="whitelist__title">
                    {#if isEditingItem}
                        <input
                            type="text"
                            class="whitelist__input-pattern"
                            pattern={REMOTE_MATCH_PATTERN_REGEX.source}
                            required
                            bind:this={editingInput}
                            bind:value={editingValue}
                            on:input={checkEditValidity}
                            on:blur={finishEditing}
                            on:keypress={ev =>
                                ev.key === "Enter" && finishEditing()}
                        />
                    {:else}
                        {item.pattern}
                    {/if}
                </div>

                {#if !isEditingItem}
                    <label class="whitelist__user-agent">
                        <input
                            type="checkbox"
                            bind:checked={item.isUserAgentDisabled}
                        />
                        {_("optionsSiteWhitelistUserAgent")}
                    </label>
                    <button
                        type="button"
                        class="whitelist__edit-button ghost"
                        title={_("optionsSiteWhitelistEditItem")}
                        disabled={isEditing && !isEditingValid}
                        on:click={() => beginEditing(i)}
                    >
                        <img src="assets/photon_edit.svg" alt="icon, edit" />
                    </button>
                {/if}

                <button
                    type="button"
                    class="whitelist__remove-button ghost"
                    title={_("optionsSiteWhitelistRemoveItem")}
                    disabled={isEditing && !isEditingItem && !isEditingValid}
                    on:click={() => removeItem(i)}
                >
                    <img src="assets/photon_delete.svg" alt="icon, remove" />
                </button>
            </li>
        {/each}
    </ul>

    <hr />

    <div class="whitelist__view-actions">
        <button
            class="whitelist__add-button ghost"
            title={_("optionsSiteWhitelistAddItem")}
            on:click={addItem}
            type="button"
        >
            <img src="assets/photon_new.svg" alt="icon, add" />
        </button>
    </div>
</div>
